CREATE TABLE IF NOT EXISTS admin_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  nombre_corto TEXT NOT NULL DEFAULT '',
  nombre_largo TEXT NOT NULL DEFAULT '',
  eslogan TEXT NOT NULL DEFAULT '',
  ciudad TEXT NOT NULL DEFAULT '',
  departamento TEXT NOT NULL DEFAULT '',
  pais TEXT NOT NULL DEFAULT 'Colombia',
  direccion TEXT NOT NULL DEFAULT '',
  correo_contacto TEXT NOT NULL DEFAULT '',
  whatsapp_numero TEXT NOT NULL DEFAULT '',
  whatsapp_mensaje TEXT NOT NULL DEFAULT '',
  agenda_url TEXT NOT NULL DEFAULT '',
  form_endpoint TEXT NOT NULL DEFAULT '/api/contacto',
  public_site_url TEXT NOT NULL DEFAULT '',
  public_gtm_id TEXT NOT NULL DEFAULT '',
  linkedin_url TEXT NOT NULL DEFAULT '',
  instagram_url TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS legal_content (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  razon_social TEXT NOT NULL DEFAULT '',
  nit TEXT NOT NULL DEFAULT '',
  representante_legal TEXT NOT NULL DEFAULT '',
  correo_habeas_data TEXT NOT NULL DEFAULT '',
  telefono_legal TEXT NOT NULL DEFAULT '',
  direccion_legal TEXT NOT NULL DEFAULT '',
  aviso_privacidad_md TEXT NOT NULL DEFAULT '',
  politica_datos_md TEXT NOT NULL DEFAULT '',
  terminos_md TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_members (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  cargo TEXT NOT NULL,
  matricula TEXT NOT NULL DEFAULT '',
  resumen TEXT NOT NULL DEFAULT '',
  bio_md TEXT NOT NULL DEFAULT '',
  foto_url TEXT NOT NULL DEFAULT '',
  orden INTEGER NOT NULL DEFAULT 0,
  publicado INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faq_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  seccion TEXT NOT NULL DEFAULT 'inicio',
  pregunta TEXT NOT NULL,
  respuesta TEXT NOT NULL,
  orden INTEGER NOT NULL DEFAULT 0,
  publicado INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS homepage_sections (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tipo TEXT NOT NULL,
  clave TEXT NOT NULL,
  titulo TEXT NOT NULL DEFAULT '',
  resumen TEXT NOT NULL DEFAULT '',
  href TEXT NOT NULL DEFAULT '',
  icono TEXT NOT NULL DEFAULT '',
  orden INTEGER NOT NULL DEFAULT 0,
  publicado INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tipo, clave)
);

CREATE TABLE IF NOT EXISTS content_entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  collection TEXT NOT NULL,
  slug TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  body_md TEXT NOT NULL DEFAULT '',
  meta_json TEXT NOT NULL DEFAULT '{}',
  orden INTEGER NOT NULL DEFAULT 0,
  publicado INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(collection, slug)
);

CREATE TABLE IF NOT EXISTS draft_revisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  scope TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  created_by TEXT NOT NULL DEFAULT 'admin',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_at TEXT
);

CREATE TABLE IF NOT EXISTS publish_jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  revision_id INTEGER,
  status TEXT NOT NULL DEFAULT 'pending',
  message TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(revision_id) REFERENCES draft_revisions(id)
);

INSERT OR IGNORE INTO site_settings (id) VALUES (1);
INSERT OR IGNORE INTO legal_content (id) VALUES (1);
